### PR TITLE
Fix 247

### LINKED ISSUE #247: A read out-of-bands was found in the parsing of TGA files
Hi,

A read out-of-bands was found in the parsing of TGA files using the last revision of libgd (a6a0e7feabb2a9738086a5dc96348f233c87fa79). Find [attached a small sample (it is a tga, not a really a txt)](https://github.com/libgd/libgd/files/341530/test.txt) to reproduce it. The ASAN report is here:

```
==25148==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62500000e91c at pc 0x7ffff6c8b446 bp 0x7fffffffdf40 sp 0x7fffffffdf38
READ of size 4 at 0x62500000e91c thread T0
    #0 0x7ffff6c8b445 in gdImageCreateFromTgaCtx /tmp/libgd/src/gd_tga.c:103
    #1 0x7ffff6c8ad26 in gdImageCreateFromTga /tmp/libgd/src/gd_tga.c:25
    #2 0x401581 in main tga/bug00084.c:10
    #3 0x7ffff686aec4 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)
    #4 0x401458 (/tmp/libgd/tests/tga/.libs/lt-bug00084+0x401458)

0x62500000e91c is located 0 bytes to the right of 8220-byte region [0x62500000c900,0x62500000e91c)
allocated by thread T0 here:
    #0 0x7ffff6f567df in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x547df)
    #1 0x7ffff6ca49e1 in gdMalloc /tmp/libgd/src/gdhelpers.c:75
    #2 0x7ffff6c8c254 in read_image_tga /tmp/libgd/src/gd_tga.c:226
    #3 0x7ffff6c8af91 in gdImageCreateFromTgaCtx /tmp/libgd/src/gd_tga.c:74
    #4 0x7ffff6c8ad26 in gdImageCreateFromTga /tmp/libgd/src/gd_tga.c:25
    #5 0x401581 in main tga/bug00084.c:10
    #6 0x7ffff686aec4 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)

SUMMARY: AddressSanitizer: heap-buffer-overflow /tmp/libgd/src/gd_tga.c:103 gdImageCreateFromTgaCtx
```

(it is not related with bug 00084, i just re-used the test case to read an arbitrary TGA file)

This issue was found using QuickFuzz.

Regards,
Gustavo.

### PR DESCRIPTION
**Pull request by oerdnj**
Fixes #247 

Before:
```
$ ./tga/bug00247 
=================================================================
==128235==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62500000e91c at pc 0x7fcfa43dd2d6 bp 0x7ffd36a97a90 sp 0x7ffd36a97a88
READ of size 4 at 0x62500000e91c thread T0
    #0 0x7fcfa43dd2d5 in gdImageCreateFromTgaCtx /home/ondrej/Projects/pkg-libgd/gd-libgd/src/gd_tga.c:103:5
    #1 0x7fcfa43dbcaf in gdImageCreateFromTga /home/ondrej/Projects/pkg-libgd/gd-libgd/src/gd_tga.c:25:10
    #2 0x4bd889 in main /home/ondrej/Projects/pkg-libgd/gd-libgd/tests/tga/bug00247.c:10:10
    #3 0x7fcfa1d96b44 in __libc_start_main /build/glibc-uPj9cH/glibc-2.19/csu/libc-start.c:287
    #4 0x4bd57c in _start (/home/ondrej/Projects/pkg-libgd/gd-libgd/tests/tga/.libs/lt-bug00247+0x4bd57c)

0x62500000e91c is located 0 bytes to the right of 8220-byte region [0x62500000c900,0x62500000e91c)
allocated by thread T0 here:
    #0 0x49fefb in malloc (/home/ondrej/Projects/pkg-libgd/gd-libgd/tests/tga/.libs/lt-bug00247+0x49fefb)
    #1 0x7fcfa44573c8 in gdMalloc /home/ondrej/Projects/pkg-libgd/gd-libgd/src/gdhelpers.c:75:9
    #2 0x7fcfa43e0aca in read_image_tga /home/ondrej/Projects/pkg-libgd/gd-libgd/src/gd_tga.c:226:24
    #3 0x7fcfa43dc42c in gdImageCreateFromTgaCtx /home/ondrej/Projects/pkg-libgd/gd-libgd/src/gd_tga.c:74:6
    #4 0x7fcfa43dbcaf in gdImageCreateFromTga /home/ondrej/Projects/pkg-libgd/gd-libgd/src/gd_tga.c:25:10
    #5 0x4bd889 in main /home/ondrej/Projects/pkg-libgd/gd-libgd/tests/tga/bug00247.c:10:10
    #6 0x7fcfa1d96b44 in __libc_start_main /build/glibc-uPj9cH/glibc-2.19/csu/libc-start.c:287

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/ondrej/Projects/pkg-libgd/gd-libgd/src/gd_tga.c:103 gdImageCreateFromTgaCtx
Shadow bytes around the buggy address:
  0x0c4a7fff9cd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4a7fff9ce0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4a7fff9cf0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4a7fff9d00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4a7fff9d10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c4a7fff9d20: 00 00 00[04]fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a7fff9d30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a7fff9d40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a7fff9d50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a7fff9d60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a7fff9d70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  ASan internal:           fe
==128235==ABORTING
Aborted (core dumped)
```

After:
```
$ ./tga/bug00247 
```

### CODE REVIEW

File: src/gd_tga.c [hunk 1]
```diff
@@ -237,7 +237,10 @@ int read_image_tga( gdIOCtx *ctx, oTga *tga )
 			return -1;
 		}
 
-		gdGetBuf(conversion_buffer, image_block_size, ctx);
+		if (gdGetBuf(conversion_buffer, image_block_size, ctx) != image_block_size) {
+			gdFree(conversion_buffer);
```
Comment (cmb69) [inline src/gd_tga.c]: Maybe we should add an error message here (and also for the RLE code below):

    gd_error("gd-tga: premature end of image data\n");

File: tests/tga/bug00247.c [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+
+int main(int argc, char **argv)
+{
+    gdImagePtr im;
+    FILE *fp = gdTestFileOpen("tga/bug00247.tga");
+    im = gdImageCreateFromTga(fp);
+    if (im != NULL)
+	gdImageDestroy(im);
+    return 0;
+}
```
Comment (cmb69) [inline tests/tga/bug00247.c]: This test doesn't seem to verify that `im` is supposed to be NULL. What about:

    im = gdImageCreateFromTga(fp);
    gdTestAssert(im == NULL);
    fclose(fp);
    return gdNumFailures();

**Comment by cmb69** [comment]
@oerdnj I had already send a very similar patch to Pierre, Remi and Mike via email. I've added a few notes to the code, where I think this PR could be improved. :)

**Comment by oerdnj** [comment]
@cmb69 Thanks, merged your changes.

File: tests/tga/bug00247.c [hunk 3]
```diff
@@ -0,0 +1,14 @@
+#include <stdio.h>
+
+#include "gd.h"
+#include "gdtest.h"
+
+int main(int argc, char **argv)
```
Comment (cmb69) [inline tests/tga/bug00247.c]: I get compile time warnings wrt. to `argc` and `argv` being unused. IIRC, that causes the build to fail in the GD-2.2 branch (or did it use to fail in master, and this has recently been changed?)

Otherwise the PR looks fine. Thanks!

Comment (oerdnj) [inline tests/tga/bug00247.c]: Unused `argc` and `argv` is all over places.  I will possibly make some time in future to do such cleanups. (Also more tests are failing with ASAN that probably also needs some attention...)

Thanks for the review, I'll merge it.
