### PR TITLE
HEIF codecs check in test suite

### LINKED ISSUE #675: heif failing tests: heif/heif_im2im & heif/heif_read
this is failing tests for me on my Gentoo system.  could you take a look @YakoYakoYokuYoku ?

```sh
$ emerge -Opvq libheif
[ebuild   R   ] media-libs/libheif-1.10.0  USE="aom go threads -gdk-pixbuf -libde265 -rav1e -test -x265"

$ ./heif/heif_im2im 
GD Warning: gd-heif encoder acquisition failed (missing codec support?)
heif/heif_im2im.c:29: return value of gdImageHeifPtrEx() is null
heif/heif_im2im.c:30: gdImageHeifPtrEx() output size is non-positive
GD Warning: gd-heif incorrect type of file
heif/heif_im2im.c:33: return value of gdImageCreateFromHeifPtr() is null
heif/heif_im2im.c:35: cannot compare with NULL buffer

$ ./heif/heif_read 
GD Warning: gd-heif decoding failed
heif/heif_read.c:18: Assert failed in <heif/heif_read.c:18>
```

### PR DESCRIPTION
**Pull request by YakoYakoYokuYoku**
Use the `heif_have_decoder_for_format` and `heif_have_encoder_for_format` functions to find if HEVC decoding/encoding is supported by `libheif`.

Fixes #675.

### CODE REVIEW

File: tests/heif/heif_im2im.c [hunk 1]
```diff
@@ -15,6 +17,9 @@ int main()
 	int size = 0;
 	CuTestImageResult result = {0, 0};
 
+	if (!gdTestAssertMsg(heif_have_decoder_for_format(heif_compression_HEVC) && heif_have_encoder_for_format(heif_compression_HEVC), "HEVC codec support missing from libheif\n"))
+		return 0;
```
Comment (vapier) [inline tests/heif/heif_im2im.c:21]: you want to return `77` instead.  this will mark the test as SKIP.

Comment (YakoYakoYokuYoku) [reply tests/heif/heif_im2im.c:21]: Ain't skipping with `ctest`, is there any other return code?

Comment (vapier) [reply tests/heif/heif_im2im.c:21]: hrm, autotest respects `77` already.  looks like we need to opt-in to it in cmake:
https://cmake.org/cmake/help/latest/prop_test/SKIP_RETURN_CODE.html

i just pushed 16fab2f35a26 which should make this work for us too.  i did a brief test and it seemed to work.

Comment (YakoYakoYokuYoku) [reply tests/heif/heif_im2im.c]: Thanks for pushing that.

**Comment by vapier** [comment]
thanks, i verified they fixed my local tests
